# Generated by Django 5.2.5 on 2025-09-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Укажите заголовок", max_length=100, verbose_name="Заголовок")),
                ("content", models.TextField(help_text="Заполните содержимое", verbose_name="Содержимое")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="blog/blogs_images",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                ("is_published", models.BooleanField(default=True)),
                ("views_count", models.IntegerField()),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["title", "created_at", "views_count", "is_published"],
            },
        ),
    ]
