# Generated by Django 5.2.5 on 2025-09-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Укажите количество просмотров", verbose_name="Счетчик просмотров"
            ),
        ),
    ]
