# Generated by Django 5.2.5 on 2025-08-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название компании")),
                ("address", models.TextField(blank=True, null=True, verbose_name="Адрес")),
                ("phone", models.CharField(blank=True, max_length=20, null=True, verbose_name="Телефон")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="catalog/product_images",
                verbose_name="Изображение",
            ),
        ),
    ]
