# Generated by Django 5.2.5 on 2025-09-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Адрес"),
        ),
    ]
